import type { StickerCategory, StickerItem } from '@/types/studio';

export const STICKER_CATEGORIES: StickerCategory[] = [
  {
    id: 'emoji',
    name: 'Emoji',
    icon: '😊',
    stickers: [
      { id: 'grinning', emoji: '😀', label: 'Grinning', category: 'emoji' },
      { id: 'joy', emoji: '😂', label: 'Joy', category: 'emoji' },
      { id: 'heart-eyes', emoji: '😍', label: 'Heart Eyes', category: 'emoji' },
      { id: 'fire', emoji: '🔥', label: 'Fire', category: 'emoji' },
      { id: 'star-struck', emoji: '🤩', label: 'Star Struck', category: 'emoji' },
      { id: 'thinking', emoji: '🤔', label: 'Thinking', category: 'emoji' },
      { id: 'cool', emoji: '😎', label: 'Cool', category: 'emoji' },
      { id: 'smiling', emoji: '😊', label: 'Smiling', category: 'emoji' },
      { id: 'screaming', emoji: '😱', label: 'Screaming', category: 'emoji' },
      { id: 'crying', emoji: '😭', label: 'Crying', category: 'emoji' },
      { id: 'wink', emoji: '😉', label: 'Wink', category: 'emoji' },
      { id: 'devil', emoji: '😈', label: 'Devil', category: 'emoji' },
      { id: 'angel', emoji: '👼', label: 'Angel', category: 'emoji' },
      { id: 'alien', emoji: '👽', label: 'Alien', category: 'emoji' },
      { id: 'clown', emoji: '🤡', label: 'Clown', category: 'emoji' },
      { id: 'ghost', emoji: '👻', label: 'Ghost', category: 'emoji' },
      { id: 'skull', emoji: '💀', label: 'Skull', category: 'emoji' },
      { id: 'poop', emoji: '💩', label: 'Poop', category: 'emoji' },
    ],
  },
  {
    id: 'love',
    name: 'Love',
    icon: '❤️',
    stickers: [
      { id: 'heart', emoji: '❤️', label: 'Heart', category: 'love' },
      { id: 'heart-pulse', emoji: '💗', label: 'Heart Pulse', category: 'love' },
      { id: 'heart-break', emoji: '💔', label: 'Heart Break', category: 'love' },
      { id: 'two-hearts', emoji: '💕', label: 'Two Hearts', category: 'love' },
      { id: 'sparkling-heart', emoji: '💖', label: 'Sparkling Heart', category: 'love' },
      { id: 'kiss', emoji: '💋', label: 'Kiss', category: 'love' },
      { id: 'cupid', emoji: '💘', label: 'Cupid', category: 'love' },
      { id: 'rose', emoji: '🌹', label: 'Rose', category: 'love' },
      { id: 'couple', emoji: '💑', label: 'Couple', category: 'love' },
      { id: 'ring', emoji: '💍', label: 'Ring', category: 'love' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    icon: '🌸',
    stickers: [
      { id: 'sun', emoji: '☀️', label: 'Sun', category: 'nature' },
      { id: 'moon', emoji: '🌙', label: 'Moon', category: 'nature' },
      { id: 'star', emoji: '⭐', label: 'Star', category: 'nature' },
      { id: 'rainbow', emoji: '🌈', label: 'Rainbow', category: 'nature' },
      { id: 'cloud', emoji: '☁️', label: 'Cloud', category: 'nature' },
      { id: 'flower', emoji: '🌸', label: 'Flower', category: 'nature' },
      { id: 'rose-flower', emoji: '🌺', label: 'Hibiscus', category: 'nature' },
      { id: 'sunflower', emoji: '🌻', label: 'Sunflower', category: 'nature' },
      { id: 'leaf', emoji: '🍃', label: 'Leaf', category: 'nature' },
      { id: 'tree', emoji: '🌳', label: 'Tree', category: 'nature' },
      { id: 'mushroom', emoji: '🍄', label: 'Mushroom', category: 'nature' },
      { id: 'butterfly', emoji: '🦋', label: 'Butterfly', category: 'nature' },
      { id: 'bee', emoji: '🐝', label: 'Bee', category: 'nature' },
      { id: 'ladybug', emoji: '🐞', label: 'Ladybug', category: 'nature' },
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    icon: '🐱',
    stickers: [
      { id: 'cat', emoji: '🐱', label: 'Cat', category: 'animals' },
      { id: 'dog', emoji: '🐶', label: 'Dog', category: 'animals' },
      { id: 'rabbit', emoji: '🐰', label: 'Rabbit', category: 'animals' },
      { id: 'panda', emoji: '🐼', label: 'Panda', category: 'animals' },
      { id: 'lion', emoji: '🦁', label: 'Lion', category: 'animals' },
      { id: 'tiger', emoji: '🐯', label: 'Tiger', category: 'animals' },
      { id: 'monkey', emoji: '🐵', label: 'Monkey', category: 'animals' },
      { id: 'fox', emoji: '🦊', label: 'Fox', category: 'animals' },
      { id: 'bear', emoji: '🐻', label: 'Bear', category: 'animals' },
      { id: 'penguin', emoji: '🐧', label: 'Penguin', category: 'animals' },
      { id: 'owl', emoji: '🦉', label: 'Owl', category: 'animals' },
      { id: 'eagle', emoji: '🦅', label: 'Eagle', category: 'animals' },
      { id: 'whale', emoji: '🐋', label: 'Whale', category: 'animals' },
      { id: 'dolphin', emoji: '🐬', label: 'Dolphin', category: 'animals' },
      { id: 'snake', emoji: '🐍', label: 'Snake', category: 'animals' },
      { id: 'unicorn', emoji: '🦄', label: 'Unicorn', category: 'animals' },
    ],
  },
  {
    id: 'food',
    name: 'Food',
    icon: '🍕',
    stickers: [
      { id: 'pizza', emoji: '🍕', label: 'Pizza', category: 'food' },
      { id: 'burger', emoji: '🍔', label: 'Burger', category: 'food' },
      { id: 'fries', emoji: '🍟', label: 'Fries', category: 'food' },
      { id: 'ice-cream', emoji: '🍦', label: 'Ice Cream', category: 'food' },
      { id: 'cake', emoji: '🎂', label: 'Cake', category: 'food' },
      { id: 'coffee', emoji: '☕', label: 'Coffee', category: 'food' },
      { id: 'donut', emoji: '🍩', label: 'Donut', category: 'food' },
      { id: 'taco', emoji: '🌮', label: 'Taco', category: 'food' },
      { id: 'sushi', emoji: '🍣', label: 'Sushi', category: 'food' },
      { id: 'popcorn', emoji: '🍿', label: 'Popcorn', category: 'food' },
      { id: 'wine', emoji: '🍷', label: 'Wine', category: 'food' },
      { id: 'beer', emoji: '🍺', label: 'Beer', category: 'food' },
      { id: 'cocktail', emoji: '🍸', label: 'Cocktail', category: 'food' },
      { id: 'watermelon', emoji: '🍉', label: 'Watermelon', category: 'food' },
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: '⚽',
    stickers: [
      { id: 'soccer', emoji: '⚽', label: 'Soccer', category: 'sports' },
      { id: 'basketball', emoji: '🏀', label: 'Basketball', category: 'sports' },
      { id: 'football', emoji: '🏈', label: 'Football', category: 'sports' },
      { id: 'baseball', emoji: '⚾', label: 'Baseball', category: 'sports' },
      { id: 'tennis', emoji: '🎾', label: 'Tennis', category: 'sports' },
      { id: 'soccer-ball', emoji: '⚽', label: 'Soccer Ball', category: 'sports' },
      { id: 'medal', emoji: '🏅', label: 'Medal', category: 'sports' },
      { id: 'trophy', emoji: '🏆', label: 'Trophy', category: 'sports' },
      { id: 'bicycle', emoji: '🚴', label: 'Bicycle', category: 'sports' },
      { id: 'swimming', emoji: '🏊', label: 'Swimming', category: 'sports' },
      { id: 'dart', emoji: '🎯', label: 'Dart', category: 'sports' },
      { id: 'gym', emoji: '💪', label: 'Gym', category: 'sports' },
    ],
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: '✈️',
    stickers: [
      { id: 'plane', emoji: '✈️', label: 'Plane', category: 'travel' },
      { id: 'globe', emoji: '🌍', label: 'Globe', category: 'travel' },
      { id: 'compass', emoji: '🧭', label: 'Compass', category: 'travel' },
      { id: 'map', emoji: '🗺️', label: 'Map', category: 'travel' },
      { id: 'beach', emoji: '🏖️', label: 'Beach', category: 'travel' },
      { id: 'mountain-travel', emoji: '🏔️', label: 'Mountain', category: 'travel' },
      { id: 'camera', emoji: '📷', label: 'Camera', category: 'travel' },
      { id: 'suitcase', emoji: '🧳', label: 'Suitcase', category: 'travel' },
      { id: 'passport', emoji: '🛂', label: 'Passport', category: 'travel' },
      { id: 'car', emoji: '🚗', label: 'Car', category: 'travel' },
    ],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    icon: '🎮',
    stickers: [
      { id: 'joystick', emoji: '🎮', label: 'Joystick', category: 'gaming' },
      { id: 'gamepad', emoji: '🕹️', label: 'Gamepad', category: 'gaming' },
      { id: 'dice', emoji: '🎲', label: 'Dice', category: 'gaming' },
      { id: 'chess', emoji: '♟️', label: 'Chess', category: 'gaming' },
      { id: 'spade', emoji: '♠️', label: 'Spade', category: 'gaming' },
      { id: 'heart-suit', emoji: '♥️', label: 'Heart Suit', category: 'gaming' },
      { id: 'diamond', emoji: '♦️', label: 'Diamond', category: 'gaming' },
      { id: 'club', emoji: '♣️', label: 'Club', category: 'gaming' },
      { id: 'trophy-gaming', emoji: '🏆', label: 'Trophy', category: 'gaming' },
      { id: 'star-gaming', emoji: '⭐', label: 'Star', category: 'gaming' },
    ],
  },
  {
    id: 'holiday',
    name: 'Festival',
    icon: '🎉',
    stickers: [
      { id: 'party', emoji: '🎉', label: 'Party', category: 'holiday' },
      { id: 'confetti', emoji: '🎊', label: 'Confetti', category: 'holiday' },
      { id: 'balloon', emoji: '🎈', label: 'Balloon', category: 'holiday' },
      { id: 'gift', emoji: '🎁', label: 'Gift', category: 'holiday' },
      { id: 'fireworks', emoji: '🎆', label: 'Fireworks', category: 'holiday' },
      { id: 'sparkler', emoji: '🎇', label: 'Sparkler', category: 'holiday' },
      { id: 'ribbon', emoji: '🎀', label: 'Ribbon', category: 'holiday' },
      { id: 'christmas', emoji: '🎄', label: 'Christmas Tree', category: 'holiday' },
      { id: 'santa', emoji: '🎅', label: 'Santa', category: 'holiday' },
      { id: 'pumpkin', emoji: '🎃', label: 'Pumpkin', category: 'holiday' },
      { id: 'diya', emoji: '🪔', label: 'Diya', category: 'holiday' },
      { id: 'lantern', emoji: '🏮', label: 'Lantern', category: 'holiday' },
    ],
  },
  {
    id: 'abstract',
    name: 'Abstract',
    icon: '🎨',
    stickers: [
      { id: 'sparkle-abs', emoji: '✨', label: 'Sparkle', category: 'abstract' },
      { id: 'crown', emoji: '👑', label: 'Crown', category: 'abstract' },
      { id: 'rainbow-abs', emoji: '🌈', label: 'Rainbow', category: 'abstract' },
      { id: 'zap', emoji: '⚡', label: 'Zap', category: 'abstract' },
      { id: 'infinity', emoji: '♾️', label: 'Infinity', category: 'abstract' },
      { id: 'atom', emoji: '⚛️', label: 'Atom', category: 'abstract' },
      { id: 'peace', emoji: '☮️', label: 'Peace', category: 'abstract' },
      { id: 'yin-yang', emoji: '☯️', label: 'Yin Yang', category: 'abstract' },
      { id: 'eye', emoji: '👁️', label: 'Eye', category: 'abstract' },
      { id: 'drop', emoji: '💧', label: 'Drop', category: 'abstract' },
    ],
  },
  {
    id: 'quotes',
    name: 'Quotes',
    icon: '💬',
    stickers: [
      { id: 'speech-bubble', emoji: '💬', label: 'Speech Bubble', category: 'quotes' },
      { id: 'thought', emoji: '💭', label: 'Thought', category: 'quotes' },
      { id: 'exclamation', emoji: '❗', label: 'Exclamation', category: 'quotes' },
      { id: 'question', emoji: '❓', label: 'Question', category: 'quotes' },
      { id: 'hundred', emoji: '💯', label: '100', category: 'quotes' },
      { id: 'muscle', emoji: '💪', label: 'Muscle', category: 'quotes' },
      { id: 'fingers-crossed', emoji: '🤞', label: 'Fingers Crossed', category: 'quotes' },
      { id: 'ok-hand', emoji: '👌', label: 'OK', category: 'quotes' },
      { id: 'peace-sign', emoji: '✌️', label: 'Peace', category: 'quotes' },
      { id: 'wave', emoji: '👋', label: 'Wave', category: 'quotes' },
    ],
  },
  {
    id: 'memes',
    name: 'Funny',
    icon: '😂',
    stickers: [
      { id: 'roll-eyes', emoji: '🙄', label: 'Roll Eyes', category: 'memes' },
      { id: 'facepalm', emoji: '🤦', label: 'Facepalm', category: 'memes' },
      { id: 'shrug', emoji: '🤷', label: 'Shrug', category: 'memes' },
      { id: 'vomiting', emoji: '🤮', label: 'Vomiting', category: 'memes' },
      { id: 'sneeze', emoji: '🤧', label: 'Sneeze', category: 'memes' },
      { id: 'zany', emoji: '🤪', label: 'Zany', category: 'memes' },
      { id: 'upside-down', emoji: '🙃', label: 'Upside Down', category: 'memes' },
      { id: 'money-mouth', emoji: '🤑', label: 'Money Mouth', category: 'memes' },
      { id: 'nerd', emoji: '🤓', label: 'Nerd', category: 'memes' },
      { id: 'party-face', emoji: '🥳', label: 'Party Face', category: 'memes' },
    ],
  },
];

export const ALL_STICKERS = STICKER_CATEGORIES.flatMap(c => c.stickers);

export function getStickerById(id: string): StickerItem | undefined {
  return ALL_STICKERS.find(s => s.id === id);
}

export function searchStickers(query: string): StickerItem[] {
  const q = query.toLowerCase();
  return ALL_STICKERS.filter(
    s => s.label.toLowerCase().includes(q) || s.emoji.includes(q) || s.category.toLowerCase().includes(q)
  );
}
